config/routes.rb
Rails.application.routes.draw do

  namespace :administrator do
      resources :users
      resources :accounts
      resources :bookings
      resources :events
      resources :posts
      resources :reports
      resources :rooms
      resources :rsvps

      root to: "bookings#index"
    end
  resources :reports, except: [:index]
  get 'rsvp/new'
  get 'rsvp/create'
  get 'rsvp/delete'
  get 'rsvp/update'
  get 'rsvp/show'
  resources :posts
  get 'avatar/create'
  get 'avatar/update'
  get 'avatar/destroy'

  resources :rooms do
      resources :bookings
      get '/confirmation', to: "bookings#confirmation"
  end
  resources :events

  # serve /site/ pages
  get '/about-us', to: "site#about", as: '/about'
  get '/contact-us', to: "site#contact", as: '/contact'
  get '/profile', to: "site#profile", as: '/profile'
  get '/dashboard', to: "site#dashboard", as: '/dashboard'
  get '/users', to: "site#users", as: '/users'
  get '/room-bookings', to: "site#room_bookings", as: '/bookings'
  get '/venues', to: "site#venues", as: '/venues'
  get '/blog', to: "site#blog", as: '/blog'
  get '/admin', to: "site#admin", as: '/admin'
  get '/maintain', to: "site#maintain", as: '/maintain'
  get '/support', to: "site#support", as: '/support'
  get '/change_profile_picture', to: "site#add_profile_picture", as: '/change_profile_picture'

  # serve user management
  devise_for :users , controllers: { registrations: "registrations" }
  resources :accounts

  # setup root page
  root to: "site#index"
  #root to: "site#maintain"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/room.rb
class Room < ApplicationRecord


    # define associations
    has_many :bookings, dependent: :destroy

    # associate model with picture of the room(many)
    has_many_attached :images, dependent: :destroy

end

app/controllers/administrator/rooms_controller.rb
module Administrator
  class RoomsController < Administrator::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   foo = Foo.find(params[:id])
    #   foo.update(params[:foo])
    #   send_foo_updated_email
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #  if current_user.super_admin?
    #    resource_class
    #  else
    #    resource_class.with_less_stuff
    #  end
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.where(room_type: "accommodation").all
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
    @booking = Booking.new
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)
    if params[:room][:images]
        @room.images.attach(params[:room][:images])
    end


    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    if params[:room][:images]
        @room.images.attach(params[:room][:images])
    end
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:room_name, :description, :amenities, :price, :booking_id, :check_in, :check_out, :room_type, :booked, :quantity)
    end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<%= form_with(model: room, local: true) do |form| %>
  <% if room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
      <% room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
      <div class="col-xs-offset-1 col-xs-10 col-sm-6 col-md-6 col-lg-6">
          <div class="row">
              <div class="col-xs-8 col-sm-6 col-md-4 col-lg-6">
                <%= form.label :room_name %> 
                <%= form.text_field :room_name, class: "form-control", placeholder: "room name" %>
                <br>
                <br>
              </div>
          </div>
      
          <div class="row">
              <div class="col-xs-8 col-sm-6 col-md-4 col-lg-6">
                <%= form.label :room_description %> 
                <%= form.text_area :description, class: "form-control", placeholder: "more details", rows: 15 %>
                <br>
                <br>
              </div>
          </div>

          <div class="row">
              <div class="col-xs-8 col-sm-6 col-md-4 col-lg-4">
                <%= form.label :price %>
                <%= form.text_field :price, class: "form-control", placeholder: "price for room" %>
                <br>
                <br>
              </div>
          </div>

          <div class="row">
              <div class="col-xs-8 col-sm-6 col-md-4 col-lg-4">
                <%= form.label :room_type %>
                <%= form.select :room_type, options_for_select(["accommodation", "venue"]), {}, class: "form-control", placeholder: "price for room" %>
                <br>
                <br>
              </div>
          </div>

      </div>

      <div class="col-xs-offset-1 col-xs-10 col-sm-6 col-md-6 col-lg-6">

          <div class="row">
              <div class="col-xs-8 col-sm-6 col-md-4 col-lg-6">
                <%= form.label :amenities %> 
                <%= form.text_area :amenities, class: "form-control", placeholder: "list amenities", rows: 15 %>
                <br>
                <br>
              </div>
          </div>
          <div class="row">
              <div class="col-sm-4 col-md-4 col-lg-6">
                    <%= form.label :allowed_checkin_time %> 
                <%= form.text_field :check_in, class: "form-control datepicker" %>
                <br><br>
              </div>
          </div>

          <div class="row">
              <div class="col-sm-4 col-md-4 col-lg-6">
                    <%= form.label :allowed_checkout_time %> 
                <%= form.text_field :check_out, class: "form-control datepicker" %>
                <br><br>
              </div>
          </div>

          <div class="row">
              <div class="col-sm-4 col-md-4 col-lg-6">
                    <%= form.label :upload_images %> 
                    <%= form.file_field :images, multiple: true %> 
                <br/><br/>
              </div>
          </div>
      
      </div>
  
  </div>

  <div class="row">
      <div class="col-xs-offset-1 col-xs-10 col-sm-4 col-md-4 col-lg-4">
        <%= form.submit "Create Room", class: "btn btn-success btn-lg" %>
      </div>
  </div>
<% end %>

app/views/rooms/edit.html.erb
<div class="container">
  <div class="text-center py-5">
      <h1 class="text-warning">Edit Room</h1>
  </div>

  <%= render 'form', room: @room %>
</div>

app/views/rooms/index.html.erb
<% title "Where to stay in Parys, Our Rooms at Partuma"%>
<% meta_tag :description, 'Stunning rooms for stay in Parys' %>
<% meta_tag :keywords, 'parys accommodation, free state lodge, vaal lodging' %>
<div class="container">
  <div class="text-center py-5">
    <h2 class="text-warning">Book one of our rooms</h2>
  </div>

  <h4 class="py-2">Standard Rooms</h4>
  <div class="card-deck py-2">
    <% @rooms.each do |room| %>
      <div class="card">
    <% if room.images.attached?%>
      <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
          <% for i in 0..room.images.count do %>
            <% if i == 0 %>
              <li data-target="#carouselExampleIndicators" data-slide-to="<%= i %>" class="active"></li>
            <% else %>
              <li data-target="#carouselExampleIndicators" data-slide-to="<%= i %>"></li>
            <% end %>
          <% end %>
        </ol>
        <div class="carousel-inner">
          <% @i = 0%>
          <% room.images.each do |img|%>
            <% if @i == 0 %>
              <div class="carousel-item active">
                <%= image_tag(img, class: "d-block w-100 img-fluid", alt: "partuma slide")%>
              </div>
              <% @i = @i + 1%>
            <% else %>
              <div class="carousel-item">
                <%= image_tag(img, class: "d-block w-100", alt: "partuma slide")%>
              </div>
            <% end %>
          <% end %>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
    <% end %>
        <div class="card-body">
          <p class="text-muted py-4"><%= room.description %></p>
          <h4 class="card-title">
            R <%= room.price %> per night
          </h4>

          <h6 class="card-title text-muted">Amenities</h6>
          <hr/>
          <ul class="list-group pb-4">
            <% room.amenities.split(",").each do |am| %>
                <li class="nav-link disabled"><%= am %></li>
            <% end %>
          </ul>
          <h6 class="card-title text-muted">Check-in Times</h6>  
          <hr/>
          <p class="card-text text-muted">
            Anytime after <%= room.check_in %>
          </p>
          <%= link_to "Book Room", room, class: "btn btn-danger btn-block" %>
          <% if user_signed_in? && current_user.admin? %>
            <%= link_to "Edit room", edit_room_path(room), class: "btn btn-warning btn-block"%>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/rooms/new.html.erb
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-3 col-md-2 col-lg-2 sidebar hidden-xs">
            <%= render 'site/sidebar' %> 
        </div>
        <div class="col-sm-offset-1 col-sm-8 col-md-8 col-lg-offset-1 col-lg-8">
            <div class="row">
                <h1 class="page-header">Add Room</h1>
            </div>

            <div class="row">
                <%= render 'form', room: @room %>
            </div>
        </div>
    </div>
</div>
<div class="row" style="height: 400px;"></div>

app/views/rooms/show.html.erb
<% title "Where to stay in Parys, Our Rooms "%>
<% meta_tag :description, @room.description %>
<% meta_tag :keywords, @room.amenities %>
<div class="container py-5">
  <div class="card py-5">
    <% if @room.images.attached?%>
      <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
          <% for i in 0..@room.images.count do %>
            <% if i == 0 %>
              <li data-target="#carouselExampleIndicators" data-slide-to="<%= i %>" class="active"></li>
            <% else %>
              <li data-target="#carouselExampleIndicators" data-slide-to="<%= i %>"></li>
            <% end %>
          <% end %>
        </ol>
        <div class="carousel-inner">
          <% @i = 0%>
          <% @room.images.each do |img|%>
            <% if @i == 0 %>
              <div class="carousel-item active">
                <%= image_tag(img, class: "d-block w-100 img-fluid", alt: "partuma slide")%>
              </div>
              <% @i = @i + 1%>
            <% else %>
              <div class="carousel-item">
                <%= image_tag(img, class: "d-block w-100", alt: "partuma slide")%>
              </div>
            <% end %>
          <% end %>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
    <% end %>
    <div class="card-body">
      <h2 class="card-title text-warning"><%= @room.room_name %></h2>
      <p class="card-text text-muted">
        <%= @room.description %>
      </p>
      <h4 class="card-title">
        R <%= @room.price %> per night
      </h4>
      <h6 class="text-muted py-4">Amenities</h6>
      <hr/>
      <ul class="list-group py-4">
        <% @room.amenities.split(",").each do |an|%>
            <li class="nav-link disabled"><%= an %></li>
        <% end %>
      </ul>
      <%= link_to "Make Reservation", new_room_booking_path(@room), class: "btn btn-primary btn-block"%>
    </div>
  </div>
  <% if user_signed_in? && current_user.admin? %>
    <h2 class="py-5 text-warning">Make Changes</h2>
    <div class="py-5">
        <%= link_to 'Edit Room', edit_room_path(@room), class: "btn btn-primary btn-lg" %> 
        <%= link_to 'Delete Room', room_path(@room), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger btn-lg"%>
        <%= link_to "Add Pictures", edit_room_path(@room), class: "btn btn-warning btn-lg"%>
    </div>
  <% end %>
</div>