config/routes.rb
Rails.application.routes.draw do

  namespace :administrator do
      resources :users
      resources :accounts
      resources :bookings
      resources :events
      resources :posts
      resources :reports
      resources :rooms
      resources :rsvps

      root to: "bookings#index"
    end
  resources :reports, except: [:index]
  get 'rsvp/new'
  get 'rsvp/create'
  get 'rsvp/delete'
  get 'rsvp/update'
  get 'rsvp/show'
  resources :posts
  get 'avatar/create'
  get 'avatar/update'
  get 'avatar/destroy'

  resources :rooms do
      resources :bookings
      get '/confirmation', to: "bookings#confirmation"
  end
  resources :events

  # serve /site/ pages
  get '/about-us', to: "site#about", as: '/about'
  get '/contact-us', to: "site#contact", as: '/contact'
  get '/profile', to: "site#profile", as: '/profile'
  get '/dashboard', to: "site#dashboard", as: '/dashboard'
  get '/users', to: "site#users", as: '/users'
  get '/room-bookings', to: "site#room_bookings", as: '/bookings'
  get '/venues', to: "site#venues", as: '/venues'
  get '/blog', to: "site#blog", as: '/blog'
  get '/admin', to: "site#admin", as: '/admin'
  get '/maintain', to: "site#maintain", as: '/maintain'
  get '/support', to: "site#support", as: '/support'
  get '/change_profile_picture', to: "site#add_profile_picture", as: '/change_profile_picture'

  # serve user management
  devise_for :users , controllers: { registrations: "registrations" }
  resources :accounts

  # setup root page
  root to: "site#index"
  #root to: "site#maintain"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord

  # define associations
  belongs_to :user
  has_many   :bookings

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord


    # define associations
    belongs_to :room, dependent: :destroy
    belongs_to :user, dependent: :destroy
end

app/models/event.rb
class Event < ApplicationRecord

    # associate model with picture of the event(many)
    has_many_attached :images
    has_many_attached :rsvps

    #validations
    validates_presence_of :name
    validates_presence_of :description
    validates_presence_of :event_date
    validates_presence_of :event_time
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  has_many_attached :images

end

app/models/report.rb
class Report < ApplicationRecord
    belongs_to :user
end

app/models/room.rb
class Room < ApplicationRecord


    # define associations
    has_many :bookings, dependent: :destroy

    # associate model with picture of the room(many)
    has_many_attached :images, dependent: :destroy

end

app/models/rsvp.rb
class Rsvp < ApplicationRecord

    belongs_to :event, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # associations
  has_one  :account, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_many :posts
  has_many :reports
  #has_many :visits, class_name: "Ahoy::Visit"


  # associate avatars with the model
  has_one_attached :avatar, dependent: :destroy
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, :user_admin?, except: [:index, :show]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.images.attach(params[:post][:images])
    @post.user_id = current_user.id

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :caption, :user_id)
    end

    def user_admin?
        return current_user.admin?
    end
end

app/controllers/rsvp_controller.rb
class RsvpController < ApplicationController

    before_action :set_event

  def new
  end

  def create

  end

  def delete
  end

  def update
  end

  def show
  end


  private

  def set_event
      @event = Event.find(params[:event_id])
  end

  def event_params
      params.require(:event).permit(:account_id, :event_id)
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  before_action :authenticate_user!, only: [:dashboard, :profile, :users, :bookings, :add_profile_picture, :support]

  def support
      @reports = Report.all
  end
  def maintain
  end
  def add_profile_picture
    @account = Account.find(params[:account_id])
  end

  def room_bookings
    @bookings = Booking.all
  end

  def blog
    @posts = Post.all
  end

  def index
  end

  def about
  end

  def dashboard
    @visits = Ahoy::Visit.where("referring_domain IS NOT NULL")
    @bookings = Booking.all
    @users  = User.all
  end

  def contact
  end

  def profile
    @user = current_user
  end

  def users
    @users = User.all
  end

  def admin

  end

  def venues
    @rooms = Room.where(room_type: "venue").all
  end

end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def title text
    content_for(:title) { text }
  end

  def meta_tag tags, text
    content_for :"meta_#{tags}", text 
  end

  def yield_meta_tag tags, default_text='' 
    content_for?(:"meta_#{tags}") ? content_for(:"meta_#{tags}") : default_text
  end
end

app/helpers/avatar_helper.rb
module AvatarHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/rsvp_helper.rb
module RsvpHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/site/_topbar.html.erb
<% if user_signed_in?%>
    <%if current_user.admin?%>
        <div class="nav">
            <ul class="nav nav-tabs">
                <li class="<%= current_page?(dashboard_path) ? 'active': ''%>"><%= link_to "Dashboard", dashboard_path %></li>
                <li  class="<%= current_page?(bookings_path) ? 'active': ''%>"role="presentation"><%= link_to "Bookings", bookings_path %></li>
                <li  class="<%= current_page?(admin_path) ? 'active': ''%>"role="presentation"><%= link_to "Admin", admin_path %></li>
                <li  class="<%= current_page?(blog_path) ? 'active': ''%>"role="presentation"><%= link_to "Blog", blog_path %></li>
                <li  class="<%= current_page?(accounts_path) ? 'active': ''%>"role="presentation"><%= link_to "Users", accounts_path %></li>
                <li  class="<%= current_page?(support_path) ? 'active': ''%>"role="presentation"><%= link_to "Support", support_path %></li>
            </ul>
        </div>
    <% end %>
<% end %>

app/views/site/about.html.erb
<div class="container">
  <div class="text-center py-5">
    <h2 class="text-warning">About Us</h2>
  </div>
  <div class="text-center py-4">
    <h4 class="text-muted">Company</h4>
    <p class="lead py-2">
      Partuma Lodge and Jazz Club is an accommodation and hospitality establishment which has been officially operating for more than 3 years under 100% woman-ownership and management. The name Partuma is a combination of two names/locations (Parys and Tumahole) and it was named so because it is situated in between Parys Town and Tumahole Township. 
    </p>
  </div>  
  <div class="text-center py-4">
      <h4 class="text-muted">Our Culture</h4>
      <p class="lead py-2">
     We share a common corporate culture, organizational goal, vision, and spirit of service excellence throughout all departments (management, reception, accommodation, conference, kitchen, housekeeping, entertainment, ground staff and security services). 
      </p>
  </div>  
  <div class="text-center py-4">
    <h4 class="text-muted">Our Vision</h4>
    <p class="lead py-2">
     Our main objective is to develop and add more facilities and increased services as we grow through the years. We strive to consistently meet the standards set out by the Tourism Grading Council of South Africa and continue to abide by the rules and regulations set out by the Free State Tourism Authority, Occupational Health and Safety and other relevant parties. 
      </p>
  </div>  
  <div class="text-center py-4">
    <h4 class="text-muted">Future Prospects</h4>
    <p class="lead py-2">
      Within the next 5 years, the establishment will expand and accommodate many more customers to their uttermost satisfaction. We will continue to improve the level of our service standard adding more stars to our reputation. We will also continue to bring bigger and better entertainment for our important customers.</p>
  </div>  
</div>

app/views/site/add_profile_picture.html.erb
<div class="container">
    <div class="row">
        <h1 class="page-header">Change profile picture</h1>
    </div>
    <div class="row">
        <%= form_tag(model: account, local: true)%> 
            
        <% end %>
    </div>
</div>

app/views/site/admin.html.erb
<% if current_user.admin? %>
<div class="container-fluid">
    <div class="row col-sm-11 col-md-11 col-lg-11 main-dashboard">
        <div class="row">
            <%= render "site/topbar"%>
        </div>

        <div class="row">
            <h2 class="page-header text-muted">Manage Events</h2>
            <%= link_to "Add Event", new_event_path, class: "btn btn-danger btn-lg"%>
            <br>
            <%= link_to "Share A Previous Event", new_post_path, class: "btn btn-danger btn-lg"%>
            <br>
        </div>

        <div class="row">
            <h2 class="page-header text-muted">Manage Rooms</h2>
            <%= link_to "Go to Rooms", rooms_path, class: "btn btn-danger btn-lg"%>
            <br>
            <br>
        </div>
        <div class="row" style="height: 200px;"></div>
    </div>
</div>
<% end %>

app/views/site/blog.html.erb
<div class="container-fluid">
    <div class="row col-sm-11 col-md-11 col-lg-11 main-dashboard">
        <div class="row">
            <%= render "topbar"%>
        </div>

        <br>
        <br>
        
        <div class="row">
            <h1 class="page-header text-muted">Posts</h1>  
            <br>
                <% if @posts.count == 0 %>
                    <div class="jumbotron">
                        <h1 class="text-center">Nothing posted yet.</h1>
                    </div>
                <%else%>
                    <% (@posts).each do |post|%>
                        <div class="media">
                            <div class="media-left">
                                <p class="text-muted pull-left lead"><%= 1 %></p>
                            </div>
                            <div class="media-body">
                                <p class="lead"><%= link_to post.title, post %></p>  
                                <p class="text-muted">created <%= time_ago_in_words(post.created_at)%> ago.</p>
                            </div>
                        </div>
                    <% end %>
                <% end %>
        </div>
    </div>
</div>
<div class="row" style="height: 200px;"></div>

app/views/site/contact.html.erb
<% title "how to book in Parys "%>
<% meta_tag :description, 'Book us for a couple of days' %>
<% meta_tag :keywords, 'Partuma, parys, wedding, hosting, venue, free state' %>
<div class="container">
  <div class="text-center py-5">
    <h2 class="text-warning">Contact Us</h2>
  </div>
  <div class="py-2 mx-2">
    <div class="alert alert-warning">
        <a class="close" href="#" data-dismiss="alert">x</a>
        <p>We are open from 07h00 until 22h00 for phone calls.</p>
    </div>
  </div>
  <div class="text-center">
    <p class="text-warning">
      <strong> Call us:</strong>
      <br/>
      +27 56 817 1123
    </p>
    <p class="text-warning">
      <strong> Email us:</strong>
      <br/>
          partuma.lodge@gmail.com
    </p>  
    <p class="text-warning">
      <strong> Address:</strong>
      <br/>
      2 Schochet St<br/>
      Parys Industria, Parys<br/>
      9585<br/>
      South Africa
    </p>  
  </div>
  <div class="text-center py-5">
    <h2 class="text-warning py-4">Find us</h2>
    <%= image_tag("maps_find_us", style: "max-width: 100%;")%>
  </div>
</div>

app/views/site/dashboard.html.erb
<% if current_user.admin? %>             
<div class="container-fluid">
    <div class="row col-sm-11 col-md-11 col-lg-11 main-dashboard">
        <div class="row">
            <%= render "topbar"%>
        </div>
        <div class="row">
            <%= pie_chart @visits.where("city IS NOT NULL and started_at > ?", 200.days.ago).group(:city).count, title: "City spread", download: true, donut: true, width: "800px", height: "500px"  %>
        </div>
        <div class="row">
            <div class="col-sm-5 col-md-5 col-lg-5">
                <%= pie_chart @visits.group(:city).count, title: "City spread", download: true, donut: true, width: "800px", height: "500px"  %>

            </div>
            <div class="col-sm-6 col-md-6 col-lg-6">
              <% sum = 0%>
              <% bsum = 0%>
              <%= line_chart [{  name: "Weekly Web Traffic", data: @visits.where("started_at > ?", 90.days.ago).group_by_day(:started_at).count}],
                               xtitle: "Date accessed", ytitle: "Total No of People", title: "Total Daily Visitors", download: true  %>
            </div>
        </div>
        <div class="row hidden-sm">
            <h1 class="text-muted page-header">Total Sign ups</h1>
            <table class="table table-striped table-bordered">
                <tr>
                    <th>Id</th>
                    <th>Name</th>
                    <th>Surname</th>
                    <th>Email</th>
                    <th>Created Date</th>
                </tr>
                <% @users.each do |user|%>
                    <% if !user.account.nil? %>
                    <tr>
                        <td><%= link_to user.id, "#"%></td>
                        <td><%= user.account.name%></td>
                        <td><%= user.account.surname%></td>
                        <td><%= user.email%></td>
                        <td><%= user.created_at.strftime("%d, %B, %Y")%></td>
                    </tr>
                    <% else %>
                    <tr>
                        <td><%= link_to user.id, "#"%></td>
                        <td></td>
                        <td></td>
                        <td><%= user.email %></td>
                        <td><%= user.created_at.strftime("%d, %B, %Y")%></td>
                    </tr>

                    <% end %>
                <% end %>
            </table>
        </div>
    </div>
</div>
<% end %>

app/views/site/events_index.html.erb
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-9 col-md-2 col-lg-2 sidebar">
            <%= render 'site/sidebar' %> 
        </div>
        <div class="col-sm-3 col-md-8 col-lg-8">
            <p id="notice"><%= notice %></p>
            <div class="row">
                <%= link_to 'Create Event', new_event_path, class: "btn btn-success btn-lg" %>
            </div>
            <div class="row">
                <h2 class="page-header"><%= pluralize(@events.count, 'Event')%></h2>
                <% @events.each do |event| %>
                    <div class="col-md-4">
                        <div class="row">
                            <h3 class="text-info"><%= link_to event.name, event %></h3>
                            <p class="lead"><%= event.description %></p>
                            <p class="lead"><%= event.event_date %>, at <%= event.event_time %></p>
                        </div>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/site/maintain.html.erb
<% if current_user.admin? %>             
<div class="row">
<div class="jumbotron">
    <h1 class="text-center text-muted">partuma.co.za</h1>
    <p class="text-center lead">Site is undergoing some technical maintenance, will be back soon.</p>
</div>
</div>
<% end %>

app/views/site/profile.html.erb
<div class="container">
    <div class="row">
        <div class="col-xs-12 col-sm-5 col-md-5 col-lg-5">
            <% if !@user.avatar.attached? %>
                <div class="row text-center">
                    <h3 class="text-muted">Add Profile Picture</h3>
                    
                    <%= link_to "Add Profile Picture", avatar_create_path, class: "btn btn-default btn-lg" %>
                </div>
            <% else %>
                <div class="row text-center">
                    <br>
                    <br>
                    <%= image_tag(current_user.avatar, class: "img-circle-profile") %>
                    <br>
                    <br>
                    <br>
                    <br>
                    <h3 class="text-muted">Settings</h3>
                    <%= link_to "Change Profile Picture", avatar_create_path, class: "btn btn-default btn-lg" %>
                </div>
            <% end %>
        </div>

        <div class="co-xs-12 col-sm-5 col-md-5 col-lg-5">
            <div class="row hidden-sm hidden-md hidden-lg" style="padding-top: 50px;"></div>
            <div class="row"> 
                <div class="co-xs-12 hidden-sm hidden-md hidden-lg" style="padding-left: 20px;">
                    <h1 class="page-header">Hello, <%= @user.account.name %></h1>
                </div>
            </div>
            <div class="row"> 
                <div class="col-xs-4 col-sm-3 col-md-2 col-lg-2 text-muted"> 
                    <p>Name:</p>
                    <p>Surname:</p>
                    <p>DOB:</p>
                    <p>email:</p>
                    <p>address:</p>
                    <br class="hidden-xs">
                    <p>cel:</p>
                </div>
                <div class="col-xs-8 col-sm-5 col-md-4 col-lg-4"> 
                    <p><%= @user.account.name%></p>
                    <p><%= @user.account.surname%></p>
                    <p><%= @user.account.dob%></p>
                    <p><%= @user.email%></p>
                    <% if @user.account.address.nil?%>
                        <p class="text-muted"><%= link_to "add address", edit_account_path(@user.account)%></p>
                    <% else %>
                        <p><%= @user.account.address%></p>
                    <% end %>
                    <p><%= @user.account.cel%></p>
                </div>
            </div>
            <div class="row">
                <div class="co-xs-12 hidden-sm hidden-md hidden-lg" style="padding-left: 20px;padding-top: 50px;">
                    <%= link_to "edit account", edit_account_path(@user.account), class: "text-danger"%>
                    <%= link_to "delete account", edit_account_path(@user.account), class: "text-muted"%>
                </div>
            </div>
            <div class="row">
                <h2 class="text-muted page-header">Previous Bookings/RSVPs</h2>
                <%= link_to "back", :back, class: "btn btn-default"%>
            </div>
        </div>
    </div>     
     
    <div class="row" style="height: 300px;"></div>
</div>

app/views/site/room_bookings.html.erb
<% if current_user.admin? %>             
<div class="container-fluid">
    <div class="col-xs-12 col-sm-11 col-md-11 col-lg-11 main-dashboard">
        <div class="row hidden-xs">
            <%= render 'site/topbar' %> 
        </div>
        <div class="row">
            <div class="row">
                <h1 class="page-header">Bookings</h1>
            </div>  

            <div class="row">
                <table class="table table-bordered">
                    <tr>
                        <th>Room Name</th>
                        <th>Customer</th>
                        <th>Age</th>
                        <th>Check-in</th>
                        <th>Check-out</th>
                        <th>Adults</th>
                        <th>Children</th>
                        <th>Price</th>
                    </tr>
                    <% @bookings.each do |booking| %>
                        <tr>
                            <td><%= link_to "User here", "#" %></td>
                            <td><%= Account.find(booking.account_id).name %>&nbsp;&nbsp;<%= Account.find(booking.account_id).surname %></td>
                            <td><%= time_ago_in_words(User.find(booking.user_id).account.dob)%></td>
                            <td><%= booking.checkin_day%></td>
                            <td><%= booking.checkout_day%></td>
                            <td><%= booking.adults%></td>
                            <td><%= booking.children%></td>
                            <td><%= booking.children%></td>
                        </tr>
                    <% end %>
                </table>
            </div>
        </div>
    </div>
</div>
<% end %>

app/views/site/support.html.erb
<% if current_user.admin? %>             
<div class="container-fluid">
    <div class="row col-sm-11 col-md-11 col-lg-11 main-dashboard">
        <div class="row">
            <%= render "topbar"%>
        </div>
        <div class="row">

            <h1 class="page-header text-muted">Monthly Reports (Website)&nbsp;&nbsp;<%= link_to "add report", new_report_path, class: "btn btn-default"%></h1>

            <% @reports.each do |report|%>
            <ul class="list">
                <li><%= link_to report.name, report %></li>
            </ul>
            <% end %>
        </div>
    </div>
</div>
<div class="row" style="height: 300px;"></div>
<% end %>

app/views/site/users.html.erb
<% if current_user.admin? %>             
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-2 col-md-2 col-lg-2 sidebar">
            <%= render 'site/sidebar' %> 
        </div>
        <div class="col-sm-8 col-md-8 col-lg-8 main-wrapper">
            <div class="row">
                <h1 class="page-header">Users</h1>
            </div>
            <table class="table table-striped table-bordered">
                <tr>
                    <th>Name</th>
                    <th>Surname</th>
                    <th>Email</th>
                </tr>
                <% @users.each do |user|%>
                    <tr>
                        <td><%= user.email%></td>
                        <td><%= user.email%></td>
                        <td><%= user.email%></td>
                    </tr>
                <% end %>
            </table>
        </div>
    </div>
</div>
<% end %>

app/views/site/venues.html.erb
<% title "Where to host a wedding, party or event, Our Venues "%>
<% meta_tag :description, 'We host your event in Parys' %>
<% meta_tag :keywords, 'Partuma, parys, wedding, hosting, venue, free state' %>
<div class="mx-2 venues">
  <div class="container">
    <div class="text-center py-5">
      <h2 class="text-warning">Celebrate your events with us</h2>
    </div>
    <div class="text-center py-4">
      <%= image_tag("page-under.png", class: "img-fluid rounded", alt: "partuma-party Responsive image")%>
    </div>
    <div class="card-deck pb-5">
      <% @rooms.each do |room| %>
        <div class="card">
          <% if room.images.attached? %>
            <%= image_tag(room.images.last,alt: "partuma lodge jazz club", style: "max-width: 100%;")%>
          <% end %>
          <div class="card-body">
            <h4 class="py-4 card-title"><%= room.room_name %></h4>
            <p class="py-4 card-text">
              <%= link_to "More Pictures", room, class: "btn btn-default pull-right" %>
            </p>
          </div>
        </div>
      <% end %>
    </div>

    <% if user_signed_in? && current_user.admin? %>
      <div class="py-5">
        <%= link_to "Add new room", new_room_path, class: "btn btn-warning btn-lg"%>
      </div>
    <% end %>
  </div>
</div>