config/routes.rb
Rails.application.routes.draw do

  namespace :administrator do
      resources :users
      resources :accounts
      resources :bookings
      resources :events
      resources :posts
      resources :reports
      resources :rooms
      resources :rsvps

      root to: "bookings#index"
    end
  resources :reports, except: [:index]
  get 'rsvp/new'
  get 'rsvp/create'
  get 'rsvp/delete'
  get 'rsvp/update'
  get 'rsvp/show'
  resources :posts
  get 'avatar/create'
  get 'avatar/update'
  get 'avatar/destroy'

  resources :rooms do
      resources :bookings
      get '/confirmation', to: "bookings#confirmation"
  end
  resources :events

  # serve /site/ pages
  get '/about-us', to: "site#about", as: '/about'
  get '/contact-us', to: "site#contact", as: '/contact'
  get '/profile', to: "site#profile", as: '/profile'
  get '/dashboard', to: "site#dashboard", as: '/dashboard'
  get '/users', to: "site#users", as: '/users'
  get '/room-bookings', to: "site#room_bookings", as: '/bookings'
  get '/venues', to: "site#venues", as: '/venues'
  get '/blog', to: "site#blog", as: '/blog'
  get '/admin', to: "site#admin", as: '/admin'
  get '/maintain', to: "site#maintain", as: '/maintain'
  get '/support', to: "site#support", as: '/support'
  get '/change_profile_picture', to: "site#add_profile_picture", as: '/change_profile_picture'

  # serve user management
  devise_for :users , controllers: { registrations: "registrations" }
  resources :accounts

  # setup root page
  root to: "site#index"
  #root to: "site#maintain"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/report.rb
class Report < ApplicationRecord
    belongs_to :user
end

app/controllers/administrator/reports_controller.rb
module Administrator
  class ReportsController < Administrator::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   foo = Foo.find(params[:id])
    #   foo.update(params[:foo])
    #   send_foo_updated_email
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #  if current_user.super_admin?
    #    resource_class
    #  else
    #    resource_class.with_less_stuff
    #  end
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_report, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /reports
  # GET /reports.json
  def index
    @reports = Report.all
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
  end

  # GET /reports/new
  def new
    @report = Report.new
  end

  # GET /reports/1/edit
  def edit
  end

  # POST /reports
  # POST /reports.json
  def create
    @report = Report.new(report_params)
    @report.user_id = current_user.id

    respond_to do |format|
      if @report.save
        format.html { redirect_to @report, notice: 'Report was successfully created.' }
        format.json { render :show, status: :created, location: @report }
      else
        format.html { render :new }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reports/1
  # PATCH/PUT /reports/1.json
  def update
    respond_to do |format|
      if @report.update(report_params)
        format.html { redirect_to @report, notice: 'Report was successfully updated.' }
        format.json { render :show, status: :ok, location: @report }
      else
        format.html { render :edit }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report.destroy
    respond_to do |format|
      format.html { redirect_to reports_url, notice: 'Report was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def report_params
      params.require(:report).permit(:name, :content, :user_id)
    end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_form.html.erb
<%= form_with(model: report, local: true) do |form| %>
  <% if report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(report.errors.count, "error") %> prohibited this report from being saved:</h2>

      <ul>
      <% report.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
      <div class="col-md-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
            <br/>
            <br/>
            <br/>
      </div>
  </div>

  <div class="row">
      <div class="col-md-5">
            <%= form.label :content %>
            <%= form.text_area :content, class: "form-control", rows: "15" %>
            <br/>
            <br/>
            <br/>
      </div>
  </div>


  <div class="row">
      <div class="col-sm-6 col-md-8 col-lg-6">
    <%= form.submit "Create Report", class: "btn btn-success"%>
    <%= link_to "Back", :back, class: "btn btn-danger"%>
      </div>
  </div>
<% end %>

app/views/reports/edit.html.erb
<div class="container">
    <div class="row">
        <h1 class="page-header">Add Report</h1>
    </div>
    <div class="row">
        <%= render 'form', report: @report %>
    </div>
</div>

app/views/reports/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reports</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Content</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reports.each do |report| %>
      <tr>
        <td><%= report.name %></td>
        <td><%= report.content %></td>
        <td><%= report.user_id %></td>
        <td><%= link_to 'Show', report %></td>
        <td><%= link_to 'Edit', edit_report_path(report) %></td>
        <td><%= link_to 'Destroy', report, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Report', new_report_path %>

app/views/reports/new.html.erb
<div class="container">
    <div class="row">
        <h1 class="page-header">Add Report</h1>
    </div>
    <div class="row">
        <%= render 'form', report: @report %>
        <br/>
        <br/>
        <br/>
        <br/>
    </div>
</div>  

app/views/reports/show.html.erb
<div class="container">
    <div class="row">
        <h1 class="page-header"><%= @report.name %></h1>
        <p class="text-muted"><%= time_ago_in_words(@report.created_at) %> ago</p>
    </div>
    <div class="row">
        <p class="lead"><%= @report.content %></p>
    </div>
    <div class="row">
    <%= link_to 'Edit', edit_report_path(@report) %> |
    <%= link_to 'Back', support_path %>
    <br/> 
    <br/> 
    <br/> 
    <br/> 
    </div>
</div>